version: '3.12.4'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: container-django-blogss
    volumes:
      - .:/app
    ports:
      - "8090:8000"